### ISSUE TITLE
TypeError: Cannot access offset of type string on string

### ISSUE THREAD

**Issue by sapillai** [wedevelopcoffee/wPower#6]
With WHMCS v8.6.1 & PHP 8.1, navigating to domains under client is resulting in this error: 

`TypeError: Cannot access offset of type string on string in /app/whmcs/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Domain/AdditionalFields.php:96
Stack trace:
#0 /app/whmcs/modules/registrars/openprovider/src/AdditionalFields.php(93): WeDevelopCoffee\wPower\Domain\AdditionalFields->getFilteredAdditionalFields()
#1 /app/whmcs/modules/registrars/openprovider/helpers.php(18): OpenProvider\WhmcsRegistrar\src\AdditionalFields->get()
#2 /app/whmcs/resources/domains/additionalfields.php(8): openprovider_additional_fields()
#3 /app/whmcs/vendor/whmcs/whmcs-foundation/lib/Domains/AdditionalFields.php(0): unknown()
#4 /app/whmcs/vendor/whmcs/whmcs-foundation/lib/Domains/AdditionalFields.php(0): WHMCS\Domains\AdditionalFields->fetch()
#5 /app/whmcs/vendor/whmcs/whmcs-foundation/lib/Domains/AdditionalFields.php(0): WHMCS\Domains\AdditionalFields->loadFieldsData()
#6 /app/whmcs/vendor/whmcs/whmcs-foundation/lib/Domains/AdditionalFields.php(0): WHMCS\Domains\AdditionalFields->setTLD()
#7 /app/whmcs/op/clientsdomains.php(0): WHMCS\Domains\AdditionalFields->setDomain()
#8 {main}`

Appears to be an issue with PHP 8 compatibility. Can it be fixed/updated?

**Comment by jamesbregenzer** [comment]
Enclose the statements causing this issue in a if condition which checks if the $tmpRegistrarFields and $whmcsField are arrays. As shown below, open your whmcs installation root folder using any ftp/file manager, and locate modules/registrars/openprovider/src/ folder, open AdditionalFields.php file, go to line number 96, and make changes as seen in below screenshot.

![mod-1](https://user-images.githubusercontent.com/12888026/210324170-3ee76d7a-cd1d-4483-8352-081af56e527f.png)
![mod-2](https://user-images.githubusercontent.com/12888026/210324177-62570a3e-ac96-4d0d-99fe-df4ea55157fe.png)

**Comment by MrKoopie** [comment]
This is indeed an issue in the openprovider module. Please check https://github.com/openprovider/Openprovider-WHMCS-domains/issues/252, as a solution might be provided there.

**Comment by maverick85** [comment]
Hi,

Can't find the specified code on the mentioned file:

https://github.com/openprovider/Openprovider-WHMCS-domains/blob/master/modules/registrars/openprovider/src/AdditionalFields.php
